In [113]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [24]:
# How many negative numbers are there?

len(a[a<0])

4

In [25]:
# How many positive numbers are there?

len(a[a>0])

5

In [26]:
# How many even positive numbers are there?

len(a[(a>0)&(a % 2 == 0)])

3

In [27]:
# If you were to add 3 to each data point, how many positive numbers would there be?

a_plus_three = (a + 3)
len(a_plus_three[a_plus_three > 0])

10

In [28]:
# If you squared each number, what would the new mean and standard deviation be?

a_squared = (a ** 2)
a_squared.mean() #74
a_squared.std() #144.02

144.0243035046516

In [115]:
# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean 
# of the data is 0. This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.

a_centered = a - a.mean()
a_centered
np.mean(a_centered) # 0. Nice.

0.0

In [30]:
# Calculate the z-score for each data point. Recall that the z-score is given by:

# Z = (x − μ) / σ

a_z_score = ( a - a.mean()) / a.std()
a_z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

###### More Numpy

In [34]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
sum_of_a

55

In [36]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
min_of_a

1

In [37]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)
max_of_a

10

In [44]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [48]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = 1

for n in a:
    product_of_a *= n
    
product_of_a

3628800

In [50]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = [n**2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [51]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [52]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [53]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [57]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
b = np.array(b)

b.sum()

33

In [58]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

b.min()

3

In [59]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

b.max()

8

In [60]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

b.mean()

5.5

In [70]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

np.product(b)

20160

In [63]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

b_squares = b ** 2
b_squares

array([[ 9, 16, 25],
       [36, 49, 64]])

In [65]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

b[b % 2 != 0]

array([3, 5, 7])

In [66]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

b[b % 2 == 0]

array([4, 6, 8])

In [68]:
# Exercise 9 - print out the shape of the array b.

b.shape

(2, 3)

In [76]:
# Exercise 10 - transpose the array b.

np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [79]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

In [80]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [87]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

c = np.array(c)
c.min() #1
c.max() #9
c.sum() #45
np.product(c) #362880

362880

In [88]:
# Exercise 2 - Determine the standard deviation of c.

c.std() #2.58

2.581988897471611

In [89]:
# Exercise 3 - Determine the variance of c.

np.var(c) #6.67

6.666666666666667

In [91]:
# Exercise 4 - Print out the shape of the array c

np.shape(c) #3x3

(3, 3)

In [92]:
# Exercise 5 - Transpose c and print out transposed result.

print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [94]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [98]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

np.sum((c * np.transpose(c)))

261

In [101]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.

np.product(c * np.transpose(c))


131681894400

In [102]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

d = np.array(d)
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [103]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [104]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [105]:
# Exercise 4 - Find all the negative numbers in d

d[d<0]

array([-90, -30, -45, -45])

In [106]:
# Exercise 5 - Find all the positive numbers in d

d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [107]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [108]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [109]:
# Exercise 8 - Print out the shape of d.

np.shape(d)

(3, 6)

In [110]:
# Exercise 9 - Transpose and then print out the shape of d.

np.shape(np.transpose(d))

(6, 3)

In [111]:
# Exercise 10 - Reshape d into an array of 9 x 2

np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])